# Generated by Django 4.2.7 on 2026-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_exchang_6e2561_idx',
            old_name='assets_asse_exchang_...',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_assetTy_b65161_idx',
            old_name='assets_asse_assetTy_...',
        ),
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
