# Generated by Django 4.2.7 on 2026-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_country_asset_industry_asset_name_asset_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='have_data',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
