# Generated by Django 5.2.12 on 2026-03-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_have_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_base_asset',
            field=models.BooleanField(default=False, help_text='Is part of the curated 100 universe'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_price_sync',
            field=models.DateField(blank=True, help_text='Date of last successful price fetch', null=True),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adj_close', models.FloatField(help_text='Adjusted closing price')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'date'], name='assets_pric_asset_i_bce09d_idx'), models.Index(fields=['date'], name='assets_pric_date_6729e9_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
