# Generated by Django 5.2.12 on 2026-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_is_base_asset_asset_last_price_sync_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cluster_id',
            field=models.IntegerField(blank=True, help_text='KMeans cluster assignment', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sigma_52',
            field=models.FloatField(blank=True, help_text='Annualized volatility (52-week)', null=True),
        ),
    ]
