# Generated by Django 5.2.12 on 2026-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_cluster_id_asset_sigma_52'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cluster_x',
            field=models.FloatField(blank=True, help_text='PCA component 1 for visualization', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='cluster_y',
            field=models.FloatField(blank=True, help_text='PCA component 2 for visualization', null=True),
        ),
    ]
