# Generated by Django 5.2.12 on 2026-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_cluster_x_asset_cluster_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_volatility_surge',
            field=models.BooleanField(default=False, help_text='True if Z-score > 2.0'),
        ),
        migrations.AddField(
            model_name='asset',
            name='volatility_median',
            field=models.FloatField(blank=True, help_text='3y median volatility (baseline)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='volatility_z_score',
            field=models.FloatField(blank=True, help_text='Z-score of current vol vs 3y history', null=True),
        ),
    ]
