# Generated by Django 5.2.12 on 2026-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='annualized_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='max_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_history',
            field=models.JSONField(blank=True, help_text='Time series data for charts', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
