server {
    listen 80;
    server_name guinea-pig-portfolio.ddnsfree.com;

    # Configuration for Certbot's HTTP-01 challenge (keep this for later)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name guinea-pig-portfolio.ddnsfree.com;

    ssl_certificate /etc/letsencrypt/live/guinea-pig-portfolio.ddnsfree.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/guinea-pig-portfolio.ddnsfree.com/privkey.pem;

    # SSL optimization settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_session_cache shared:SSL:10m;

    location /api/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # Use "https" explicitly here so Django knows it's secure
    proxy_set_header X-Forwarded-Proto https; 
}

    location /static/ {
        alias /app/static/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}